name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          IMAGE_TAG=$(date +%s)  # Store timestamp in a variable
          docker build . --file Dockerfile --tag python-app:$IMAGE_TAG  # Use the variable
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      
    - name: Start the Flask app in the background
      run: |
          docker run -d -p 5000:5000 python-app:$IMAGE_TAG  # Run the app with the unique tag

    - name: Call /version endpoint
      run: |
          response=$(curl -s http://localhost:5000/version)
          echo "Response from /version: $response"
          
    
